[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name   tail
    Path   /tmp/fairtrade.binlog
    Parser  none
    Tag    fairtrade.binlog

[OUTPUT]
    Name  http
    Match fairtrade.binlog
    Host  127.0.0.1
    Port  8000
    URI   /logs
    Format json
